#!/bin/bash
echo "请先配置GitHub认证："
echo "1. 生成Personal Access Token: https://github.com/settings/tokens"
echo "2. 或者配置SSH密钥: https://github.com/settings/keys"
echo ""
echo "然后运行以下命令："
echo "git config --global user.name \"你的用户名\""
echo "git config --global user.email \"你的邮箱\""
echo ""
echo "使用Token推送："
echo "git remote set-url origin https://你的token@github.com/Githubxinwei/chess_game.git"
echo "git push -u origin main"
echo ""
echo "或使用SSH推送："
echo "git remote set-url origin git@github.com:Githubxinwei/chess_game.git"
echo "git push -u origin main"